### ISSUE TITLE
Take Notify.gov out of pilot

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-api#1053]
This decision lies outside the team, so the work for the team is in preparing a justification memo, then (potentially) ushering it through a decision process. 

- [x] https://github.com/GSA/notifications-api/issues/1195
- [x] Socializing "Confirming beta" result - what does this entail?
- [ ] Something something content

**Comment by ecayer** [comment]
Hey @stvnrlly I think this needs a) socializing according to LBS's request and b) @CathyBeil to make this ✨real✨ via a blog post. Is there anything else we need to do to consider ourselves a real product?

**Comment by ecayer** [comment]
Still a potential task to tell partners, but may roll that into a pricing notification. Closing!
