### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-api#1264]
Carlo's original text:

## Improve logging

- [x] [#1268](https://github.com/GSA/notifications-api/issues/1268) Investigate our current logging configuration with Flask and look over the [Flask Handling Application Errors Guide](https://flask.palletsprojects.com/en/3.0.x/errorhandling/) to see if there is anything else we could be doing with the newer version of Flask that we're now running:  
- [x] [#1271](https://github.com/GSA/notifications-api/issues/1271)  Read over [Python 3.12's Logging Guide](https://docs.python.org/3/howto/logging.html) and see if there's anything else we could be leveraging/configuring to improve how logging is structured throughout our applications
- [x] [#1276](https://github.com/GSA/notifications-api/issues/1276) Look into [Werkzeug's documentation](https://werkzeug.palletsprojects.com/) and see if there are any tools or improvements we could be leveraging; for instance, Werkzeug supports [colorized log output based on status codes](https://werkzeug.palletsprojects.com/en/3.0.x/serving/#colored-logging)
- [x] #1328

**Comment by xlorepdarkhelm** [comment]
I put additional notes in #1065 for improiving the logging and error handling in the application.

**Comment by ecayer** [comment]
@terrazoon Is the next step for @ccostino / @stvnrlly to review #1065 and give feedback or a green light?

**Comment by ecayer** [comment]
We think this is done. Closing!
