### ISSUE TITLE
Message parts to messages

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1427]
**NB: Stuff behind the login first please!** 
As a part of our pricing plan for partners, we're going to be adjusting the way we look at and calculate the sending of messages.  Instead of calculating quotas and costs by message parts or fragments, we're going to shift to just calculating based on messages alone.

Note "message parts" may also appear in the UI as "usage"....

## For the backend

 -  [ ] Quota & usage calculations should be based on just messages, not message parts
     - [ ] Pre-send quota checks
     - [ ] Quota values in database
     - [ ] Quota setting when service is created
 
 -  [ ] Maintain a record of message parts for our own accounting purposes
 - [ ] [Update default quota to 100,000 free messages from 250,000 message parts 1540](https://github.com/GSA/notifications-api/issues/1540)

## For the frontend & docs

Should mention only messages and no message parts now:

 - [ ] Review and update Send message flow 
 - [ ] Review and update Using Notify 
 - [ ] Review and update the Dashboard
 - [ ] [Message status, daily chart...](https://github.com/orgs/GSA/projects/20/views/1?filterQuery=2204&pane=issue&itemId=90894624&issue=GSA%7Cnotifications-admin%7C2204)
 - [x] #1543
 - [ ] Review and update Onboarding materials
 - [ ] [remove "message parts" reference on Contact us page 2305](https://github.com/GSA/notifications-admin/issues/2305)
 - [ ] [determine purpose of step 4 on Using Notify landing page 2306](https://github.com/GSA/notifications-admin/issues/2306)
 - [ ] [update message part content on "Trial mode" page 2307](https://github.com/GSA/notifications-admin/issues/2307)
 - [ ] [update copy in 'Message length' accordion box component 2312](https://github.com/GSA/notifications-admin/issues/2312)
 

## For partnership & comms
 - [ ] Update MOU and IAA to not use message parts anymore (updated; need final OGC/etc approvals)
 - [ ] Let partners know this is coming & about the conversion 
 - [x]  Do we need to get partners on the new MOU or can we just roll them over progressively? (should be able to roll them over progressively)

**Comment by ccostino** [comment]
@stvnrlly this is the start of the messages parts to messages epic - please feel free to adjust with any other details you may have!

**Comment by ecayer** [comment]
Paging @CathyBeil and @dmvancura who may have thoughts on how to roll out this change... (feel free to add a comment or edit the description directly)

**Comment by ecayer** [comment]
Ooops, we had a second epic going briefly! The one additional note is that we will ideally also have some way to grant additional messages (in particular, one partner is already over their quota by the new calculation but not by the message parts calculation. According to the agreement they signed, they should still have a few left to experiment if they want).

**Comment by ecayer** [comment]
Open questions: does this include code or just content visible to users?
This is mostly about quotas & tracking... so yes, code changes to make sure we're getting the right info to display to the user

User-facing components to update:
Send flow
Dashboard
Documentation
Admin panel

**Comment by ecayer** [comment]
Answering "Decide if we want to give any visibililty into message parts at all (& do what we decide :) )" with a provisional "no" -- later we may want some site admin visibility.

**Comment by heyitsmebev** [comment]
Just adding a note for later regarding the usage page and bringing message parts into the platform admin instead.

https://gsa-tts.slack.com/archives/C0107UC0W1M/p1737671650055409

![Image](https://github.com/user-attachments/assets/01579f56-2a48-45ab-a121-bb8cd0109b1b)

**Comment by dmvancura** [comment]
in a separate epic we could track the changes needed in the "platform admin" view changes
