### ISSUE TITLE
Message send processing improvements

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1508]
With many of the immediate stability issues taken care of, we've uncovered some follow-on work that we need to dig into further.  This is work that gets to the heart of the performance and stability issues we were seeing in the first place and will help the application scale to the level that it needs to for the future.

- [ ] https://github.com/GSA/notifications-api/issues/1507
- [ ] https://github.com/GSA/notifications-api/issues/1391
- [ ] https://github.com/GSA/notifications-api/issues/1452
- [ ] https://github.com/GSA/notifications-api/issues/1494
- [ ] Create way to stop an in-progress job from continuing to process

**Comment by ecayer** [comment]
Can I suggest that with the addition of time-slicing different jobs, we postpone the "Create way to stop an in-progress job" story, @ccostino

**Comment by ccostino** [comment]
Turns out the last couple of items here are already in flight - @terrazoon has been working on them!
