### ISSUE TITLE
Reduce Tech Debt

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#361]
- [ ] https://github.com/GSA/notifications-api/issues/375
- [x] Identify obsolete code - how can we document this?
- [ ] Improve existing tests to make sure they are not UK-based
- [x] https://github.com/GSA/notifications-admin/issues/638
- [ ] [Audit site and CI/CD scans for a11y](https://github.com/GSA/notifications-admin/issues/700)
- [ ] Assess writing fuzzing to test with fake data.Can possibly do this with [pytest parametrized](https://docs.pytest.org/en/7.3.x/how-to/parametrize.html) tests and using another tool called [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) (nice to have, but not a must have)
- [x] Create a better code documentation review process
- [x] Do an infrastructure tour
- [x] [Get other folks access to necessary infra systems](https://github.com/GSA/notifications-api/issues/381)

**Comment by tdlowden** [comment]
Will de-couple some items into individual tasks and close

**Comment by ccostino** [comment]
Closing this epic in favor of these new ones!

- https://github.com/GSA/notifications-api/issues/1004
- https://github.com/GSA/notifications-api/issues/1005
