### ISSUE TITLE
Cleaning and preparing data for self-service partners (improve how we access data)

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#943]
Acceptance criteria:
- [ ] Data model for usage is clean in the API, flowing from agreements down to services
- [ ] Data querying is well-documented and simplified, ideally using one endpoint

Data model and quota management:
- [ ] #570 
- [ ] #569 
- [ ] #568 
- [ ] #354 
- [ ] #645 
- [ ] Switch services back to trial mode if their agreement expires
- [ ] ADR: How we calculate agreement/service usage - real-time vs. near-time

**Comment by ecayer** [comment]
Not expecting to do this now.
