### ISSUE TITLE
Decision on rearchitecting report generation (for stability and performance)

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#950]
Partners are still experiencing problems with report downloads, especially partners who do lots of one-off sends. The team has already made some temporary fixes, but we are still getting notice of report failures.

We believe that this is coming from reaching system limitations of processing lots of CSVs, and we would like to find a new approach.

This epic is about exploring alternative possibilities and coming to a decision about a go-forward approach for reporting.

Any decision still needs to take into account constraints around PII and cloud.gov resources,  

## Enhancements to report generation

- [ ] Explore technical possibilities
- [ ] Explore compliance possibilities ([#1838](https://github.com/GSA/notifications-admin/issues/1838))
- [ ] Write ADR for the desired approach

## Potential additional considerations. 
We may later want to...
-  Switch time-based reports to be anonymized
-  Implement an approach for anonymizing batch data
-  Add capabilities for more detailed information in batch reports for when users need it:
   - Option 1: provide the ability to re-upload the original CSV and then created a CSV report with the information stitched together
   - Option 2: provide a one-time report upon job completion that contains all of the info only at that time

**Comment by ecayer** [comment]
1. making what we have work well, 2. where do we go?

For 2, all partners care about is the phone number. Need to do research with partners about what's acceptable/useful. 

Closing this one, not going to make changes now, goes to short-term improvements (async report generation) and research for high-volume use cases
